// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database


type Role struct {
	RoleID      int32  `json:"role_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type User struct {
	UserID       int64  `json:"user_id"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	RoleID       int32  `json:"role_id"`
}
