// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

type User struct {
	ID                int32  `json:"id"`
	Name              string `json:"name"`
	Email             string `json:"email"`
	Encryptedpassword string `json:"encryptedpassword"`
}
